project_id = "mhekcxrveyijeelxavpe"

[functions.nba-stats]
verify_jwt = false

[functions.populate-players]
verify_jwt = false

[functions.populate-stats]
verify_jwt = false

[functions.bulk-populate]
verify_jwt = false

[functions.parlays]
verify_jwt = false

[functions.sync-completed-games]
verify_jwt = false

[functions.smart-sync]
verify_jwt = false